### ISSUE TITLE
Either update documentation or fix config handling

### ISSUE THREAD

**Issue by nodomain** [acockburn/occusim#2]
Setting the "test" variable to "0" does not work as expected. Test mode is still on because in the code only the existence of the variable is tested, not the actual value.
Having this in mind, the documentation is correct ("set the variable to any value"). 
But it cost me 2 days of debugging ;)

So it would be great if you could elaborate it a bit or fix the variable handling.

See https://community.home-assistant.io/t/occusim-appdaemon-just-notifies-but-does-not-switch-lights/9776/4 for the thread.

Thanks for that great appDaemon thing 👍

**Comment by acockburn** [comment]
As frustrating as this was for you, I'm not sure what to fix here? The code works as per the docs - maybe I can add a warning or something in the docs?

**Comment by nodomain** [comment]
Just add a hint in the docs then so that others have a better experience 😉

**Comment by acockburn** [comment]
It's an easy enough fix - I'll add it to the next version.
