### ISSUE TITLE
Enable flag

### ISSUE THREAD

**Issue by PianSom** [acockburn/occusim#8]
Hi

Please forgive if this is naive/wrong - I am new to Python and Appdaemon

I have looked at the code and - as far as I understand it - events are scheduled at (default) 3am for the coming day if "enable" is true at that time. They are then carried out as scheduled, regardless of whether "enable" is true at the time of event execution. Is this correct?

If so, this is not an especially family-friendly behaviour. My lot look askance at devices turning on/off at random times when they are around. Might it not be sensible to check the "enable" state at the time of execution?

**Comment by acockburn** [comment]
Yes, you are not wrong. I can add this in the next version.

**Comment by PianSom** [comment]
That's great - thanks! :) 

If you don't mind, can I ask a follow-up? I have been implementing Occusim today and have a random operation timetable set up as per your documentation [here](https://github.com/acockburn/occusim). I have an on operation called random_<random_name>_on/off_1, with a random_<random_name>_number of '4' to control a light. All good so far.

If I put in a second operation random_<random_name>_on/off_2 will your code cope with operating a second light properly on the random schedule parameters? It was not obvious to me that every "on" would be matched with an "off" of the same light. But - as I say - I am a newbie around here.

**Comment by acockburn** [comment]
It should be fine - the name matches them together.

**Comment by PianSom** [comment]
OK, excellent. Thanks.

(One small suggestion - it may be helpful to pass the function name to the log (alongside the time, etc) That way it'd be clear what will be run when)

**Comment by acockburn** [comment]
I double checked this and in fact your initial assertion is wrong, the events won;t run if the enable input boolean is switched off. The key is that I use constraints on the scheduler call to achieve this. here is the code in question:

```python
                if "enable" in self.args:
                    args["constrain_input_boolean"] = self.args["enable"]
                if "days" in events[event]["args"]:
                    args["constrain_days"] = events[event]["args"]["days"]
                self.run_at(self.execute_step, start, **args)
```

As you can see, the self.run_at() schedular call is added with a constraint that forces it to check the state of the input boolean if supplied at execution time. Closing this issue.
